"""fix patient relationship

Revision ID: 514e05873a3e
Revises: bac9da0274a8
Create Date: 2025-07-07 16:02:26.559331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514e05873a3e'
down_revision: Union[str, None] = 'bac9da0274a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('email', sa.String(), nullable=True))
    op.alter_column('patients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_patients_id', table_name='patients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_patients_id', 'patients', ['id'], unique=False)
    op.alter_column('patients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('patients', 'email')
    # ### end Alembic commands ###
