"""fix patient relationship

Revision ID: 5d79bd87a5f1
Revises: 514e05873a3e
Create Date: 2025-07-08 09:24:44.496263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d79bd87a5f1'
down_revision: Union[str, None] = '514e05873a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'email')
    # ### end Alembic commands ###
