"""fix patient relationship

Revision ID: abb6ddb81a0b
Revises: 5d79bd87a5f1
Create Date: 2025-07-08 11:10:37.857939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abb6ddb81a0b'
down_revision: Union[str, None] = '5d79bd87a5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('symptoms', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'symptoms')
    # ### end Alembic commands ###
