"""fix patient relationship

Revision ID: bac9da0274a8
Revises: 4733c364a31b
Create Date: 2025-07-07 14:43:19.052238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac9da0274a8'
down_revision: Union[str, None] = '4733c364a31b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.add_column('appointments', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.drop_index('ix_appointments_id', table_name='appointments')
    op.create_foreign_key(None, 'appointments', 'patients', ['patient_id'], ['id'])
    op.drop_column('appointments', 'reason')
    op.drop_column('appointments', 'symptoms')
    op.drop_column('appointments', 'patient_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('patient_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('symptoms', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_index('ix_appointments_id', 'appointments', ['id'], unique=False)
    op.drop_column('appointments', 'patient_id')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
